name: Deploy A React App to Vultr

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: SSH into the server
          uses: appleboy/ssh-action@master
          with:
            host: 155.138.233.237
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: | 
                cd /var/www/portfolio
                git pull origin main